name: Update Index

on:
  repository_dispatch:
    types: [package_released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout index repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # - name: Get package config
      #   run: |
      #     curl -L \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #       https://api.github.com/repos/${{ github.event.client_payload.repository }}/contents/config.json?ref=${{ github.event.client_payload.tag }} \
      #       -o config.json

      # - name: Setup npm
      #   run: |
      #     npm install

      - name: Update index.json
        run: |
          node update-index.js
        env:
          REPO_NAME: ${{ github.event.client_payload.repository }}
          TAG_NAME: ${{ github.event.client_payload.tag }}

    # - name: Commit changes
    #   run: |
    #     git config user.name "GitHub Action"
    #     git config user.email "action@github.com"
    #     git add index.json
    #     git commit -m "Update index for ${{ github.event.client_payload.repository }} ${{ github.event.client_payload.tag }}"
    #     git push
